#Gradle
org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=2g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
#org.gradle.configureondemand=true

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableR8.fullMode=false

# Kotlin
kotlin.code.style=official

# Ksp
ksp.incremental=true
ksp.incremental.log=true

#systemProp.http.proxyHost=
#systemProp.http.proxyPort=80
#systemProp.https.proxyHost=
#systemProp.https.proxyPort=80
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false
