package com.zhangke.utopia.activitypubapp.screen.service

import androidx.lifecycle.ViewModel
import com.zhangke.framework.composable.LoadableState
import com.zhangke.utopia.activitypubapp.model.ActivityPubUser
import com.zhangke.utopia.activitypubapp.uri.user.ActivityPubUserUri
import com.zhangke.utopia.activitypubapp.utils.WebFinger
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import javax.inject.Inject

@HiltViewModel
internal class ServerDetailViewModel @Inject constructor() : ViewModel() {

    private val user = ActivityPubUser(
        uri = ActivityPubUserUri.create("123", WebFinger.create("@strawberry@cmx.im")!!),
        username = "strawberry",
        displayName = "strawberry",
        locked = false,
        bot = false,
        discoverable = true,
        group = false,
        createdAt = "2019-10-18T00:00:00.000Z",
        note = "<p>长毛象中文站管理组 :cmx_00: <br />Mastodon Chinese (cmx.im) admin team</p><p>Header image © Jonathan Bertaud<br />Avatar generated by AI</p>",
        homePageUrl = "https://m.cmx.im/@strawberry",
        avatar = "https://media.cmx.edu.kg/accounts/avatars/000/000/001/original/1e29fb22eeadd91c.png",
        avatarStatic = "https://media.cmx.edu.kg/accounts/avatars/000/000/001/original/1e29fb22eeadd91c.png",
        header = "https://media.cmx.edu.kg/accounts/headers/000/000/001/original/05b2242773d63cec.jpg",
        headerStatic = "https://media.cmx.edu.kg/accounts/headers/000/000/001/original/05b2242773d63cec.jpg",
        followingCount = 39,
        followersCount = 20374,
        statusesCount = 185,
        lastStatusAt = "2023-06-30",
    )

    private val _uiState = MutableStateFlow(
        LoadableState.Success(
            ServerDetailUiState(
                domain = "m.cmx.im",
                title = "长毛象中文站",
                description = "长毛象中文站是一个开放、友好、有爱的社区。长毛象中文站主题为喵、汪、各种动物、社交、科技、编程及生活。我们欢迎友好、热情、乐于分享的朋友，无论你的兴趣点是什么。",
                thumbnail = "https://m.cmx.im/packs/media/images/preview-6399aebd96ccf025654e2977454f168f.png",
                version = "3.4",
                activeMonth = 10511,
                languages = listOf("zh-cn", "en"),
                contract = ServerDetailContract(
                    email = "public@cmx.im",
                    account = user
                ),
                rules = emptyList(),
            )
        )
    )
    val uiState: StateFlow<LoadableState<ServerDetailUiState>> = _uiState

}
