name: Check CI

on:
  pull_request:
    paths-ignore:
      - 'documents/**'
      - '**.md'

concurrency:
  group: ${{ github.event.pull_request.number }}-check-ci
  cancel-in-progress: true

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Assemble
        run: ./gradlew assembleRelease --stacktrace
