name: Check CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Assemble
        run: ./gradlew assembleRelease --stacktrace
